### ISSUE TITLE
Did you crop raw samples on the z axis?

### ISSUE THREAD

**Issue by zhangwang997** [ycwu1997/MC-Net#1]
Thank you for your work and sharing the code. But I have a question about data preprocessing. 

The [paper](https://arxiv.org/pdf/2109.09960.pdf)says that "we cropped the 3D samples according to the ground truth, with enlarged margins i.e. [10 ∼ 20, 10 ∼ 20, 5 ∼ 10] or **[25, 25, 25]** voxels on LA or PancreasCT, respectively", but [your preprocessing code](https://github.com/ycwu1997/MC-Net/blob/9517cf22522682063e8a0f9d7b31bb5d10599519/MC-Net/data/Pancreas/Pre-processing.ipynb) just cropped the samples on the x axis and y axis. 

Why they are different? Which method is used to produce the performance reported in the paper, like 91.07 on LA and 79.37 on PancreasCT?

**Comment by ycwu1997** [comment]
Hi Wang,
Thanks for your interest. You are right. I cropped the slices on Pancreas-CT only at the X and Y axes. The relevant description of the details should be a typo in the paper. I will modify that in the future version. This setting is similar to the DTC model for fair comparisons, see https://ojs.aaai.org/index.php/AAAI/article/view/17066.
Meanwhile, on the LA dataset, the pre-processing part https://github.com/ycwu1997/MC-Net/blob/main/MC-Net/code/dataloaders/la_heart_processing.py  is similar to the compared UA-MT, DTC models.
Note that, all experiments in this paper followed the same settings and used the same data inputs. If any issues, feel free to contact me. Thanks.
Yicheng
