### ISSUE TITLE
请问可以提供预处理好的Pancreas数据吗？

### ISSUE THREAD

**Issue by ant1dote** [ycwu1997/MC-Net#10]
您好，我对您的MC-Net工作非常感兴趣。请问您能提供一下这个Pancreas的数据吗？

**Comment by ycwu1997** [comment]
您好，不好意思，由于数据源限制，请在https://wiki.cancerimagingarchive.net/display/Public/Pancreas-CT 下载原始数据，我们的数据预处理脚本可以在这里查看：https://github.com/ycwu1997/MC-Net/blob/main/data/Pancreas/Pre-processing.ipynb. 谢谢。
