### ISSUE TITLE
Asking for the CT-82 dataset

### ISSUE THREAD

**Issue by Oubit1** [ycwu1997/MC-Net#11]
Hello author, I am a first-year graduate student at Zhejiang Sci-Tech University. Currently, I am working on semi-supervised medical image segmentation. While replicating your network, I have encountered difficulty in obtaining the complete CT-82 dataset. I could only access around 80 cases. In order to ensure the rigor of my experiments, I would like to request your assistance in obtaining the complete dataset.

**Comment by ycwu1997** [comment]
Yes, the rest two samples are from the same patient in the previous cases. I suggest you can conduct experiments in your own setting and just use the currently available 80 samples. Meanwhile, you can find the rest two samples here: https://drive.google.com/file/d/1qzFUtkHx-46kFvHE7RAMhjAdo6dmn4iT/view?usp=sharing. Regards -Yicheng
