### ISSUE TITLE
 Pancreas dataset preprocessing success,but the DICE score fluctuated around 0.2 to 0.1 during training.

### ISSUE THREAD

**Issue by Oubit1** [ycwu1997/MC-Net#12]
When reproducing the experiments of MC-Net on the Pancreas dataset, I used your data preprocessing file. Since I downloaded the data in the .nii.gz format, I only used the latter part of the code in the Pre-processing.ipynb notebook. After successfully modifying the code for preprocessing, I found that the average DICE score fluctuated around 0.2 to 0.1 during training. I wanted to ask if you have encountered such a situation, or if it is possible for you to provide the preprocessed Pancreas dataset? My email is [455201284@qq.com](mailto:455201284@qq.com).
![QQ截图20230625195847](https://github.com/ycwu1997/MC-Net/assets/114571962/388e2522-6013-4ff1-8c63-f999aba6fd69)

**Comment by ycwu1997** [comment]
You may need to check whether the resampling and CT-window norm. have been applied to your data. You can show your input images using the "writer.add_images" function in the training code and check the range. Note that, pls follow the augmentation way of this repo. on the Pancreas-CT dataset. Thanks.

**Comment by Oubit1** [comment]
I wrote a visualization program and discovered that the labels and data may not be aligned. I debugged the program and confirmed my suspicion. I have made changes to the preprocessing and reading steps, and I believe this should resolve the issue.

**Comment by Oubit1** [comment]
The problem didn't solved

**Comment by Oubit1** [comment]
I re-downloaded the .dcm dataset and its corresponding labels from the official website. I can confirm that they are identical to the files I am using in practice, and I also addressed the issue of missing preprocessing file associations. However, the results of model training still remain within the range of 0.1 to 0.2, indicating that the problem has not been resolved.
![QQ截图20230630174846](https://github.com/ycwu1997/MC-Net/assets/114571962/6730843d-50fc-40b0-b4b4-47409b3d4552)

**Comment by Oubit1** [comment]
Alternatively, is it possible to provide me with at least one set of corresponding labeled data, so that I can visualize and check if it matches the data I am using? (Labels corresp
![Uploading QQ截图20230630175249.png…]()
onding to the images) (mailto:455201284@qq.com).

**Comment by Oubit1** [comment]
Alternatively, is it possible to provide me with at least one set of corresponding labeled data, so that I can visualize and check if it matches the data I am using? (Labels corresponding to the images) (
![QQ截图20230630175249](https://github.com/ycwu1997/MC-Net/assets/114571962/33a0b6fd-70fa-4419-9def-9117b692894a)
mailto:455201284@qq.com).

**Comment by ycwu1997** [comment]
OK, I will find several testing samples for your reference. Good luck

**Comment by Oubit1** [comment]
The problem has beed solved ,Thanks
