### ISSUE TITLE
关于Multi-scale MC-Net+和sharpening函数问题请教

### ISSUE THREAD

**Issue by abcxubu** [ycwu1997/MC-Net#13]
有两个问题想麻烦向您请教一下。问题1：您在胰腺分割实验部分提出了Multi-scale MC-Net+方法，不知能否麻烦您分享更多关于该算法的细节（如深监督的层数、是否用了Luo算法中的对于无标签数据的损失函数等等）。问题2：我尝试使用了您文中的互一致性算法，发现它效果很好，不知能否麻烦您推荐些功能类似于sharpening的函数（或相关资料）。期待您的回复，十分感谢~

**Comment by ycwu1997** [comment]
Here, we also applied the deep supervision as URPC and the mutual consistency loss at each scale as our setting to perform such a multi-scale version. You can check our next paper (see https://github.com/ycwu1997/SS-Net) to use similar functions as sharpening, i.e., for low-entropy constraints.
