### ISSUE TITLE
Number of classes issue

### ISSUE THREAD

**Issue by Hrant3** [ycwu1997/MC-Net#15]
Hi. I read your paper and code and in the paper it is mentioned that for ACDC dataset you tried to solve 3 class segmentation problem. But in the code I see num_classes=4, did try to understand why it's 4 not 3 couldn't. Can you please elaborate? Thank you.

**Comment by ycwu1997** [comment]
One extra background class, as the setting in https://github.com/HiLab-git/SSL4MIS. Thanks.
