### ISSUE TITLE
Labels for unlabeled data

### ISSUE THREAD

**Issue by Hrant3** [ycwu1997/MC-Net#16]
Hi, I want to test mcnet2d model on my in-house dataset and I have one question regarding of use of unlabeled data. Code was running successfully with ACDC data because all images had labels but when using my in-house dataset it throws error because unlabeled data in my case doesn't have labels. Question is would it be ok if I use random labels for unlabeled data? Thanks

**Comment by ycwu1997** [comment]
Random labels cannot evaluate the performance of given unlabeled data. You can only output the predictions and ignore the performance evaluation part. If you apply random labels, the obtained performance is not reliable. Thanks.

**Comment by Hrant3** [comment]
Thank you, what if I divide my labeled data 80/20 and train my model with 80% labeled + unlabeled data and then evaluate on remaining 20?

**Comment by ycwu1997** [comment]
That would be fine
