### ISSUE TITLE
训练标签问题

### ISSUE THREAD

**Issue by RY-97** [ycwu1997/MC-Net#17]
![image](https://github.com/ycwu1997/MC-Net/assets/88662555/68c7ccb8-c064-4c3d-9a6e-ba785db50bb2)
![image](https://github.com/ycwu1997/MC-Net/assets/88662555/0fdf13c5-7fc1-40ad-9613-15a3b4f72300)
wei'sh为什么我把标签大小改成4 8就不行呢 反而2和4可以？

**Comment by ycwu1997** [comment]
pls do debug first and check the shapes of the prediction and label. It seems the shapes are not the same.
