### ISSUE TITLE
Data preparation for ACDC, LA and Pancreas

### ISSUE THREAD

**Issue by SilenceMonk** [ycwu1997/MC-Net#6]
As I'm new in this field, I can't prepare the data for the code to run. Could you offer a more detailed guideline for it? Great thanks

**Comment by ycwu1997** [comment]
Pls refer to https://github.com/HiLab-git/SSL4MIS/tree/master/data/ACDC and https://github.com/yulequan/UA-MT/blob/master/code/dataloaders/la_heart_processing.py as a reference. I also put the pre-processing codes for Pancreas at https://github.com/ycwu1997/MC-Net/blob/main/data/Pancreas/Pre-processing.ipynb. Thanks.

**Comment by SilenceMonk** [comment]
Many thanks! Also, where can I download the Pancreas dataset?

**Comment by ycwu1997** [comment]
As paper mentioned, you can find the data at https://wiki.cancerimagingarchive.net/display/Public/Pancreas-CT. Meanwhile, there are two repetitive patient-level samples in the original one (as the current paper and compared methods used). You can send an email to me, and I will send you them. Or, you can customize your own settings, just to ensure fair comparisons. Thanks.

**Comment by SilenceMonk** [comment]
Great thanks again! My email address is silencemonkg@gmail.com, maybe you can send them to me.

**Comment by ZhenZHAO** [comment]
> As paper mentioned, you can find the data at https://wiki.cancerimagingarchive.net/display/Public/Pancreas-CT. Meanwhile, there are two repetitive patient-level samples in the original one (as the current paper and compared methods used). You can send an email to me, and I will send you them. Or, you can customize your own settings, just to ensure fair comparisons. Thanks.

Hi Yicheng, @ycwu1997, I am also trying to reproduce the experiments on Pancreas. Can you also share me the deleted cases #25 and #70 for fair comparison? at zhen.zhao@outlook.com

Thanks,

Zhen

**Comment by ycwu1997** [comment]
Done; please check your email. Thanks -Yicheng

> > As paper mentioned, you can find the data at https://wiki.cancerimagingarchive.net/display/Public/Pancreas-CT. Meanwhile, there are two repetitive patient-level samples in the original one (as the current paper and compared methods used). You can send an email to me, and I will send you them. Or, you can customize your own settings, just to ensure fair comparisons. Thanks.
> 
> Hi Yicheng, @ycwu1997, I am also trying to reproduce the experiments on Pancreas. Can you also share me the deleted cases #25 and #70 for fair comparison? at [zhen.zhao@outlook.com](mailto:zhen.zhao@outlook.com)
> 
> Thanks,
> 
> Zhen
