### ISSUE TITLE
Type error when training VNet with 10% LA dataset

### ISSUE THREAD

**Issue by shinomiya-akirawane** [ycwu1997/MC-Net#7]
I get this error message when I use this `python ./code/train_mcnet_3d.py --dataset_name LA --model vnet --labelnum 8 --gpu 1,2 --temperature 0.1` command to train the model :
```
Traceback (most recent call last):
  File "/home/zhaoyan/MC-Net/./code/train_mcnet_3d.py", line 146, in <module>
    loss_seg += F.cross_entropy(y[:labeled_bs], label_batch[:labeled_bs])
  File "/home/zhaoyan/anaconda3/envs/VNet/lib/python3.9/site-packages/torch/nn/functional.py", line 3026, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: Expected floating point type for target with class probabilities, got Long
```

**Comment by ycwu1997** [comment]
Do you follow the version of python and pytorch? You can do a transformation (Long->Float) according to this error here. Meanwhile, the CE loss is just shown here and not included during the model training.  You can directly delete these related codes.

**Comment by shinomiya-akirawane** [comment]
After I commit the loss_seg, there is a new error message:
`Traceback (most recent call last):
  File "/home/zhaoyan/MC-Net/./code/train_mcnet_3d.py", line 147, in <module>
    loss_seg_dice += dice_loss(y_prob[:,1,...], label_batch[:labeled_bs,...] == 1)
  File "/home/zhaoyan/MC-Net/code/utils/losses.py", line 5, in Binary_dice_loss
    intersection = 2 * torch.sum(predictive * target) + ep
RuntimeError: The size of tensor a (2) must match the size of tensor b (112) at non-singleton dimension 1`

**Comment by shinomiya-akirawane** [comment]
The tensot a is `tensor([[[0.0094, 0.0129, 0.0148,  ..., 0.0104, 0.0110, 0.0102],
         [0.0078, 0.0092, 0.0045,  ..., 0.0089, 0.0092, 0.0069],
         [0.0054, 0.0058, 0.0087,  ..., 0.0116, 0.0114, 0.0071],
         ...,
         [0.0087, 0.0107, 0.0076,  ..., 0.0150, 0.0129, 0.0111],
         [0.0094, 0.0073, 0.0089,  ..., 0.0057, 0.0117, 0.0067],
         [0.0085, 0.0109, 0.0082,  ..., 0.0091, 0.0103, 0.0077]],

        [[0.0026, 0.0038, 0.0028,  ..., 0.0045, 0.0039, 0.0065],
         [0.0071, 0.0027, 0.0018,  ..., 0.0040, 0.0035, 0.0042],
         [0.0011, 0.0021, 0.0004,  ..., 0.0037, 0.0030, 0.0043],
         ...,
         [0.0095, 0.0077, 0.0096,  ..., 0.0067, 0.0060, 0.0072],
         [0.0070, 0.0137, 0.0070,  ..., 0.0090, 0.0042, 0.0060],
         [0.0094, 0.0063, 0.0086,  ..., 0.0103, 0.0050, 0.0078]]],
       device='cuda:0', grad_fn=<SelectBackward0>)`
The tensor b is:
`tensor([[[[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         ...,

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]]],


        [[[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         ...,

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]],

         [[False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          ...,
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False],
          [False, False, False,  ..., False, False, False]]]], device='cuda:0')`
