### ISSUE TITLE
Train VNet with all 80 labels

### ISSUE THREAD

**Issue by shinomiya-akirawane** [ycwu1997/MC-Net#9]
Sorry to raise issues again.
When I try to train the Vnet with all 80 labels, I get this error message:
```
Traceback (most recent call last):
  File "/home/zhaoyan/MC-Net/./code/train_mcnet_3d.py", line 111, in <module>
    batch_sampler = TwoStreamBatchSampler(labeled_idxs, unlabeled_idxs, args.batch_size, args.batch_size-labeled_bs)
  File "/home/zhaoyan/MC-Net/code/dataloaders/dataset.py", line 327, in __init__
    assert len(self.secondary_indices) >= self.secondary_batch_size > 0
AssertionError
```
The reason is that zero is passed to the init function of TwoStreamBatchSampler class. Am I using the wrong method to train the model?

**Comment by ycwu1997** [comment]
Such a two-stream sampling strategy is only used for semi-supervised settings (a batch contains labeled and unlabeled data at the same time). You don't have any unlabeled data in your scenario, so just using the original sampling strategy of pytorch is fine.
